apiVersion: apps/v1
kind: Deployment
metadata:
  name: mju-global-board-be
  namespace: mju-board
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mju-global-board-be
  template:
    metadata:
      labels:
        app: mju-global-board-be
    spec:
      containers:
        - name: mju-global-board-be
          image: 3tmdwn3/mju-global-board-be:e95309622d3ee6ce3bd0f58aafd543bd5d9fb5e9
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            # 필요하면 프로파일, DB 설정 등 여기 추가
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

---
apiVersion: v1
kind: Service
metadata:
  name: mju-global-board-be
  namespace: mju-board
spec:
  selector:
    app: mju-global-board-be
  ports:
    - port: 8080
      targetPort: 8080
