apiVersion: apps/v1
kind: Deployment
metadata:
  name: mju-global-board-fe
  namespace: mju-board
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mju-global-board-fe
  template:
    metadata:
      labels:
        app: mju-global-board-fe
    spec:
      containers:
        - name: mju-global-board-fe
          image: YOUR_DOCKERHUB_USERNAME/mju-global-board-fe:initial
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mju-global-board-fe
  namespace: mju-board
spec:
  selector:
    app: mju-global-board-fe
  ports:
    - port: 80
      targetPort: 80
