apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mju-global-board-ingress
  namespace: mju-board
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: mju-board.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mju-global-board-fe
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: mju-global-board-be
                port:
                  number: 8080
